[mcp_servers.axon]
args = [
    "serve",
    "--watch",
]
command = "axon"

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
SENA_AI_VENV_SCRIPTS = 'C:\Users\Admin\Downloads\sena-mobile\sena-mobile\SENA_AI\.venv\Scripts'
VIRTUAL_ENV = 'C:\Users\Admin\Downloads\sena-mobile\sena-mobile\SENA_AI\.venv'
