"""Single-pass test harness for the PSR Report service (uses example.json).

ONE Bedrock pass produces everything:
  • output/report.html        — raw HTML (what the API returns)
  • output/report.md          — merged Markdown report (readable)
  • output/usage_token.json   — aggregate token totals (what the API exposes)
  • output/usage_sections.json — PER-SECTION tokens + time (internal diagnostics)

It also runs the offline unit checks (stats/linter) and the cheap, non-Bedrock
API endpoints (health, trend save/list, auth) via the FastAPI TestClient.

The report is generated by calling the REAL production code path
(api_main._generate_report). Per-section usage is captured by wrapping
api_main._run_one *here in the test only* — api_main.py is never modified.

Toggles:
  SKIP_LLM=1  → skip the Bedrock report pass (offline + endpoint checks only)

Run:
    cd /home/main/SENA/services/casenote_monthly
    /home/main/SENA/ai-sena/bin/python test.py
"""
import asyncio
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

SKIP_LLM = os.getenv("SKIP_LLM") == "1"

# ── Load example.json (file starts with a U+200B zero-width space) ─────────────
raw = json.loads((HERE / "example.json").read_bytes().lstrip(b"\xe2\x80\x8b").decode("utf-8"))
EXAMPLE_DATA = raw.get("data", raw)
CLIENT_ID = EXAMPLE_DATA.get("client", {}).get("id", "test-client-id")
ORG_ID = "test-org-id"
DATE_FROM = EXAMPLE_DATA.get("dateFrom", "2026-05-01")
DATE_TO = EXAMPLE_DATA.get("dateTo", "2026-05-31")
PERIOD = DATE_FROM[:7]

PASS, FAIL, INFO = "\033[32m✓\033[0m", "\033[31m✗\033[0m", "\033[34m·\033[0m"


def section(t): print(f"\n{'─'*60}\n  {t}\n{'─'*60}")
def ok(m): print(f"  {PASS}  {m}")
def fail(m): print(f"  {FAIL}  {m}")
def info(m): print(f"  {INFO}  {m}")


# ── Mock the backend fetch so the (cheap) API tests use example.json ──────────
def _mock_fetch_client_data_all(*args, **kwargs):
    return {
        "data": EXAMPLE_DATA.get("data", EXAMPLE_DATA),
        "client": EXAMPLE_DATA.get("client", {"id": CLIENT_ID, "clientName": "Test Client"}),
        "pagination": {"currentPage": 1, "totalPages": 1, "hasNext": False, "limit": 30},
        "dateFrom": DATE_FROM,
        "dateTo": DATE_TO,
    }


with patch("api_main.validate_jwt", return_value=(True, None, {"sub": "test-user"})), \
     patch("api_main._fetch_client_data_all", side_effect=_mock_fetch_client_data_all):

    from fastapi.testclient import TestClient
    import api_main
    from config import MODEL_ID

    client = TestClient(api_main.app, raise_server_exceptions=False)
    results: dict[str, object] = {}

    # ── Wrap _run_one to capture per-section tokens + timing (test-only) ───────
    _section_usage: list[dict] = []
    _orig_run_one = api_main._run_one

    async def _instrumented_run_one(i, sec, subs, client_id):
        t0 = time.monotonic()
        idx, text, usage = await _orig_run_one(i, sec, subs, client_id)
        _section_usage.append({
            "section": idx,
            "inputTokens": usage.get("inputTokens", 0),
            "outputTokens": usage.get("outputTokens", 0),
            "totalTokens": usage.get("inputTokens", 0) + usage.get("outputTokens", 0),
            "elapsed_sec": round(time.monotonic() - t0, 2),
            "chars": len(text),
        })
        return idx, text, usage

    api_main._run_one = _instrumented_run_one

    # ── OFFLINE: stats.py ──────────────────────────────────────────────────────
    section("OFFLINE: stats.py")
    try:
        from stats import classify_trend, compute_stats, fulfillment, parse_hhmm
        assert parse_hhmm("09:30") == 570 and parse_hhmm("25:99") is None
        ok("parse_hhmm")
        assert fulfillment(3, 4) == 0.75 and fulfillment(3, 0) is None
        ok("fulfillment")
        assert classify_trend([0, 1]) == "insufficient"
        ok("classify_trend")
        stats = compute_stats(EXAMPLE_DATA, DATE_FROM, DATE_TO)
        ok(f"compute_stats: caseNotes={stats['caseNotes']['total']} "
           f"shifts={stats['shifts']['deliveredShifts']['completed']}")
        results["stats"] = True
    except Exception as e:
        fail(f"stats: {e}")
        results["stats"] = False

    # ── OFFLINE: linter.py ──────────────────────────────────────────────────────
    section("OFFLINE: linter.py")
    try:
        from linter import lint
        cleaned, viol = lint("Client cannot do this and was aggressive.")
        assert viol
        ok(f"lint replaced {len(viol)} term(s): {viol}")
        results["linter"] = True
    except Exception as e:
        fail(f"linter: {e}")
        results["linter"] = False

    # ── OFFLINE: anti-hallucination payload bound ─────────────────────────────
    section("OFFLINE: curated evidence payload (anti-hallucination)")
    try:
        ev = json.loads(api_main._build_evidence(EXAMPLE_DATA, stats))
        assert "shifts" not in ev and "incidents" not in ev, "raw arrays leaked!"
        ok(f"no raw countable arrays; keys={list(ev.keys())}")
        results["evidence"] = True
    except Exception as e:
        fail(f"evidence: {e}")
        results["evidence"] = False

    # ── TEST 1: health (cheap, no Bedrock) ────────────────────────────────────
    section("TEST 1 — GET /psr-report/health")
    try:
        resp = client.get("/psr-report/health")
        assert resp.status_code == 200 and resp.json().get("status") == "ok"
        ok(f"status=200  body={resp.json()}")
        results["health"] = True
    except Exception as e:
        fail(str(e)); results["health"] = False

    # ── TEST 2: full report — single Bedrock pass via _generate_report ────────
    section("TEST 2 — generate report  (real Bedrock, single pass — ~60s)")
    if SKIP_LLM:
        info("skipped (SKIP_LLM=1)")
        results["report"] = None
    else:
        info(f"client={CLIENT_ID}  period={PERIOD}")
        info("sections 1–6 parallel, then 7; per-section usage captured")
        print()
        t0 = time.time()
        try:
            html, totals = asyncio.run(
                api_main._generate_report(EXAMPLE_DATA, CLIENT_ID, PERIOD)
            )
            wall = round(time.time() - t0, 2)

            out = HERE / "output"; out.mkdir(exist_ok=True)

            # 1. raw HTML
            (out / "report.html").write_text(html, encoding="utf-8")
            ok(f"saved → output/report.html  (raw, {len(html):,} chars)")

            # 2. markdown (from the canonical report written by _generate_report)
            md_src = api_main.REPORTS_DIR / f"{CLIENT_ID}_report.md"
            if md_src.exists():
                (out / "report.md").write_text(md_src.read_text(encoding="utf-8"), encoding="utf-8")
                ok(f"saved → output/report.md  ({md_src.stat().st_size:,} bytes)")

            # 3. token totals (what the API exposes)
            usage_totals = {
                "model": MODEL_ID,
                "client_id": CLIENT_ID,
                "period": f"{DATE_FROM} → {DATE_TO}",
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "wall_clock_sec": wall,
                "totals": {
                    "inputTokens": totals["inputTokens"],
                    "outputTokens": totals["outputTokens"],
                    "totalTokens": totals["totalTokens"],
                },
            }
            (out / "usage_token.json").write_text(json.dumps(usage_totals, indent=2), encoding="utf-8")
            ok(f"saved → output/usage_token.json  (total={totals['totalTokens']:,} tokens)")

            # 4. PER-SECTION tokens + time (captured via wrapped _run_one)
            per_section = {
                f"section_{u['section']}": {k: v for k, v in u.items() if k != "section"}
                for u in sorted(_section_usage, key=lambda u: u["section"])
            }
            usage_sections = {
                "model": MODEL_ID,
                "client_id": CLIENT_ID,
                "period": f"{DATE_FROM} → {DATE_TO}",
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "wall_clock_sec": wall,
                "sections": per_section,
                "totals": usage_totals["totals"],
            }
            (out / "usage_sections.json").write_text(json.dumps(usage_sections, indent=2), encoding="utf-8")
            ok(f"saved → output/usage_sections.json  ({len(per_section)} sections)")

            # quick HTML structure + per-section summary
            ok(f"html headers={html.count('<h2>')} tables={html.count('<table>')} bullets={html.count('<li>')}")
            print()
            info(f"wall-clock {wall}s   (parallel wave 1 + sequential section 7)")
            for name, s in per_section.items():
                info(f"{name}: in={s['inputTokens']:<5} out={s['outputTokens']:<5} "
                     f"total={s['totalTokens']:<5} {s['elapsed_sec']}s")
            results["report"] = True
        except Exception as e:
            import traceback
            fail(f"{type(e).__name__}: {e}")
            traceback.print_exc()
            results["report"] = False

    # ── TEST 3 + 4: trend endpoints (cheap, no Bedrock) ───────────────────────
    section("TEST 3 — POST /psr-report/trend/save")
    try:
        resp = client.post(
            "/psr-report/trend/save",
            json={"client_id": CLIENT_ID, "period": "2026-04",
                  "trend_text": "## 5. Trend Analysis\n\nApril baseline."},
            headers={"Authorization": "Bearer test-token"},
        )
        assert resp.status_code == 200
        ok(f"status=200  {resp.json()}")
        results["trend_save"] = True
    except Exception as e:
        fail(str(e)); results["trend_save"] = False

    section("TEST 4 — GET /psr-report/trend/{client_id}")
    try:
        resp = client.get(f"/psr-report/trend/{CLIENT_ID}",
                          headers={"Authorization": "Bearer test-token"})
        if resp.status_code == 200:
            body = resp.json()
            ok(f"status=200  count={body.get('count')}  periods={[e['period'] for e in body.get('trends', [])]}")
            results["trend_list"] = True
        elif resp.status_code == 404:
            info("404 — no trend data yet")
            results["trend_list"] = None
        else:
            fail(f"status={resp.status_code}"); results["trend_list"] = False
    except Exception as e:
        fail(str(e)); results["trend_list"] = False

    # ── Summary ────────────────────────────────────────────────────────────────
    section("SUMMARY")
    labels = {
        "stats": "offline stats", "linter": "offline linter", "evidence": "anti-hallucination payload",
        "health": "GET  /psr-report/health", "report": "report generation (+ all 4 output files)",
        "trend_save": "POST /psr-report/trend/save", "trend_list": "GET  /psr-report/trend/{client_id}",
    }
    all_ok = True
    for k, label in labels.items():
        v = results.get(k)
        if v is True: ok(label)
        elif v is None: info(f"{label}  (skipped / n/a)")
        else: fail(label); all_ok = False
    print()
    print("  \033[32mAll checks passed.\033[0m" if all_ok else "  \033[31mSome checks failed.\033[0m")
    if not SKIP_LLM and results.get("report"):
        print("\n  Outputs in output/:  report.html  report.md  usage_token.json  usage_sections.json")
