-- Database Initialization Script (scripts/init_db.sql)
--
-- Purpose: Creates PostgreSQL extensions and restricted application user
-- Runs automatically when PostgreSQL container starts
--
-- Extensions created:
-- 1. pgvector - For vector embeddings (semantic search, RAG)
-- 2. uuid-ossp - For UUID generation
--
-- User/Role: sena_app
-- - Non-superuser (critical for Row Level Security to work)
-- - Has login permission
-- - Password: localdev (development only)
-- - Granted minimal permissions: SELECT, INSERT, UPDATE, DELETE on tables
-- - Lacks superuser privileges (superusers bypass RLS policies)
--
-- Note: The 'sena' superuser is for migrations only, never used at runtime
--
-- Permissions granted to sena_app:
-- - CONNECT to sena_ai database
-- - USAGE on public schema
-- - CRUD operations on tables (enforced by RLS policies)
